### ISSUE TITLE
core dumped(user/libpcap/libpcap-1.7.4) in alipinelinux docker image.

### ISSUE THREAD

**Issue by nizq** [pfq/PFQ#21]
I am using pfq in coreos. If I use ubuntu:14.04 as base docker image, everything is OK. But, if I use alpine:3.3 as base docker image, libpcap was core dumped.

gcc -v output in ubuntu:14.04 :

```
/source# gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
```

gcc -v output in alpine:3.3 :

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/5.3.0/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-5.3.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 5.3.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-esp --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib
Thread model: posix
gcc version 5.3.0 (Alpine 5.3.0) 
```

strace messages:

```
/source # PFQ_GROUP=42 strace tcpdump -n -i pfq:ens3
execve("/usr/local/sbin/tcpdump", ["tcpdump", "-n", "-i", "pfq:ens3"], [/* 9 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7f67d4eafda8) = 0
set_tid_address(0x7f67d4eafde0)         = 2253
open("/usr/local/lib/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld-musl-x86_64.path", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0555, st_size=2196888, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0z\6\0\0\0\0\0"..., 960) = 960
mmap(NULL, 4308992, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f67d480b000
mmap(0x7f67d4bfc000, 176128, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x1f1000) = 0x7f67d4bfc000
mmap(0x7f67d4c23000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f67d4c23000
close(3)                                = 0
open("/usr/local/lib/libpcap.so.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=363592, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\212\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2428928, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f67d45ba000
mmap(0x7f67d4808000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x4e000) = 0x7f67d4808000
mmap(0x7f67d480a000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f67d480a000
close(3)                                = 0
open("/usr/local/lib/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=87976, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0!\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2187264, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f67d43a4000
mmap(0x7f67d45b8000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x14000) = 0x7f67d45b8000
close(3)                                = 0
open("/usr/local/lib/libpfq.so", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=32912, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \33\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2125824, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f67d419d000
mmap(0x7f67d43a2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x5000) = 0x7f67d43a2000
close(3)                                = 0
mprotect(0x7f67d4bfc000, 114688, PROT_READ) = 0
mprotect(0x7f67d4808000, 4096, PROT_READ) = 0
mprotect(0x7f67d4eae000, 4096, PROT_READ) = 0
mprotect(0x7f67d45b8000, 4096, PROT_READ) = 0
mprotect(0x7f67d43a2000, 4096, PROT_READ) = 0
mprotect(0x55c2c05a2000, 122880, PROT_READ) = 0
open("/etc/localtime", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
mmap(NULL, 118, PROT_READ, MAP_SHARED, 3, 0) = 0x7f67d4ead000
close(3)                                = 0
ioctl(1, TIOCGWINSZ, {ws_row=44, ws_col=173, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=44, ws_col=173, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{"[PFQ] running on device ens3", 32}, {"...\n", 4}], 2[PFQ] running on device ens3...
) = 36
writev(1, [{"[PFQ] configuration file (null)", 31}, {"...\n", 4}], 2[PFQ] configuration file (null)...
) = 35
writev(1, [{"[PFQ] capture length forced to 1"..., 35}, {"\n", 1}], 2[PFQ] capture length forced to 1514
) = 36
writev(1, [{"[PFQ] buffer_size = 0 caplen = 1"..., 83}, {"\n", 1}], 2[PFQ] buffer_size = 0 caplen = 1514, rx_slots = 4096, tx_slots = 4096, tx_fhint = 1
) = 84
socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 3
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7ffeb19873f8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

gdb messages:

```
/source # PFQ_GROUP=42 gdb tcpdump
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tcpdump...done.
(gdb) r  -n -i pfq:ens3
Starting program: /usr/local/sbin/tcpdump -n -i pfq:ens3
[PFQ] running on device ens3...
[PFQ] configuration file (null)...
[PFQ] capture length forced to 1514
[PFQ] buffer_size = 0 caplen = 1514, rx_slots = 4096, tx_slots = 4096, tx_fhint = 1

Program received signal SIGSEGV, Segmentation fault.
0x00007fffffffd988 in ?? ()
(gdb) info stack
#0  0x00007fffffffd988 in ?? ()
#1  0x00007ffff771ab76 in string_for_each_token () from /usr/local/lib/libpcap.so.1
#2  0x00007ffff771c151 in pfq_activate_linux () from /usr/local/lib/libpcap.so.1
#3  0x00007ffff771e12e in pcap_activate () from /usr/local/lib/libpcap.so.1
#4  0x0000555555589bd1 in main (argc=<optimized out>, argv=0x7fffffffec88) at ./tcpdump.c:1679
(gdb) 
```

It seems that `set_promisc`(nested function) caused the error, So I used `LDFLAGS=-z execstack` to compile libpcap-1.7.4, but no help.

**Comment by pfq** [comment]
Hello,

Thanks for reporting this issue. Are you using the master or the
experimental branch? As far as I remember, I fixed some bugs in the libpcap
(in experimental) and it is also almost ready to become the next stable.
Could you give it a try?

N.

**Comment by nizq** [comment]
OK, I will try experimental branch.  Thanks.

**Comment by awgn** [comment]
nizq, have you already had the chance to test the experimental branch?

**Comment by nizq** [comment]
Same as master branch. 

In ubuntu or debian, all are OK. It should not be caused by PFQ. 

Please close this issue. I will track this problem in alpinelinux.

**Comment by awgn** [comment]
Ok, I'm closing this ticket right now. Please reopen it in case you find something wrong with the pfq-pcap library implementation. Thanks.
